### PR TITLE
Add random url choosing

### PR DESCRIPTION
**Pull request by Ratismal**
This implements a system where you can input multiple URLs (delimited by semicolons) for uploads/shortening. Upon execution, the script will choose one of these URLs to return to you.

Also fixed a thing in the `shortenset` function where it was checking if `finishstring` was equal to "q" instead of `shortenstring`.

### CODE REVIEW

**Comment by Ratismal** [comment]
Don't pull I'm still working out some kinks

**Comment by Ratismal** [comment]
Ok it should be good now

**Comment by aurieh** [comment]
You could also grab a list of domains off https://whats-th.is/public-cdn-domains.txt

**Review by islacantwin — CHANGES_REQUESTED** [review]
the screenshot/upload randomization works, but the shortening gives the error ```
/usr/local/bin/owo: line 60: 30437 % awau.moe thats-a.link : syntax error: invalid arithmetic operator (error token is ".moe thats-a.link ")```

and gives the URL `https://awau.moe;thats-a.link/0e71e7`

**Comment by Ratismal** [comment]
Fixed @OkashiOdayakana 

I had forgotten the # when retrieving the array length, did `${arr[@]}` instead of `${#arr[@]}`

**Comment by islacantwin** [comment]
@Ratismal ok, will check

**Comment by islacantwin** [comment]
Looks good.

**Pull request merged**
